import * as actions from './actions.js';
import _ from 'lodash';
import { combineReducers } from 'redux';

const initialState = {
    _app_initialized: false,
    "ApproveBookingRequest": "approved",
    "FormCreateBookingsEndpoint": {"Id":null,
"listing_id":null,
"booking_date":null,
"checkout_session_id":null,
"guest_id":null,
"status":null,
"request":null},
    "FormCreateCalendarsEndpoint": {"Id":null,
"property_id":null,
"month":null,
"year":null,
"date":null},
    "FormDeleteBookingsEndpoint": {"id":null},
    "FormDeleteCalendarsEndpoint": {"id":null},
    "FormGetOneBookingsEndpoint": {"id":null},
    "FormGetOneCalendarsEndpoint": {"id":null},
    "FormGetOneHelpPostsEndpoint": {"id":null},
    "FormGetOnePropertyImagesEndpoint": {"id":null},
    "FormUpdateBookingsEndpoint": {"status":null,
"request":null,
"Id":null,
"listing_id":null,
"booking_date":null,
"checkout_session_id":null,
"guest_id":null},
    "FormUpdateCalendarsEndpoint": {"property_id":null,
"month":null,
"year":null,
"date":null,
"Id":null},
    "FormUpdateUsersEndpoint": {"last_log_in_date_time":null,
"bio":null,
"partner_site_id":null,
"Id":null,
"last_name":null,
"password":null,
"first_name":null,
"stripe_customer_id":null,
"type_of_user":null,
"email":null,
"phone number":null,
"profilePicture":null},
    "Loading": false,
    "alert": true,
    "connectExpress": "https://connect.stripe.com/express/oauth/authorize?response_type=code&client_id=ca_M4PB8yaPIcafDgQL1z2izVR1boFI465U",
    "createListingEPI": {"guest_limit":null,
"price":null,
"order_type_id":null,
"partnerSiteId":null,
"check_in_time_id":null,
"check_out_time_id":null},
    "createPropertyEPI": {"address":null,
"city":null,
"name":null,
"description":null,
"zip":null,
"amenity":null,
"land_type":null,
"state":null,
"status":null,
"acres":null,
"images":null},
    "currentProperty": 0,
    "dataUnavailable": {"property_id":null,
"month":null,
"year":null,
"date":null,
"Id":null},
    "dateAvailable": {"property_id":null,
"month":null,
"year":null,
"date":null,
"Id":null},
    "false": false,
    "getListingsFromPartner": {"description":null,
"order_type_id":null,
"guest_limit":null,
"listing_id":null,
"zip":null,
"images":null,
"land_type":null,
"status":null,
"acres":null,
"amenity":null,
"city":null,
"property_id":null,
"creator_id":null,
"partner_site_id":null,
"property_name":null,
"address":null,
"state":null,
"price":null},
    "httpSuccessCode": 200,
    "isLoggedIn": false,
    "isNotLoggedIn": false,
    "listingUpdated": "Success! You have updated your listing!",
    "loginEPI": {"email":null,
"password":null},
    "modalCloseBooking": true,
    "modalShowBooking": false,
    "modalShowListing": true,
    "modalShowProperty": false,
    "perDayValue": 1,
    "perHourValue": 2,
    "read": false,
    "rejectBooking": "reject",
    "requestPasswordResetEPI": {"email":null},
    "selectedAmenity": false,
    "selectedProperty": true,
    "signUpEPI": {"password":null,
"email":null,
"firstName":null,
"lastName":null},
    "true": true,
    "updateListingsEPI": {"check_in_id":null,
"check_out_id":null,
"guest_limit":null,
"order_type_id":null,
"price":null},
    "updatePropertyEPI": {"status":null,
"creator_id":null,
"city":null,
"state":null,
"zip":null,
"name":null,
"description":null,
"address":null,
"amenity":null,
"land_type":null},
    "updateUserEmail": "",
    "us_states": {"Id":null,
"State":null,
"Abbreviation":null},
    "userHasNoProperty": false,
};

const reducerMain = (state = initialState, action = {}) => {
    const {type, payload} = action;
    if(type === actions.remove_field) {
        const newState = _.cloneDeep(state);
        const deleted = _.unset(newState, payload.key);
        if(!deleted) {
            console.warn(`Could not remove field at ${payload.key}`);
        }

        return newState;
    } else if (type === actions.change_input) {
        return _.setWith(_.clone(state), payload.name, payload.value, _.clone)
    }
   
    return state;
}

const reducer = combineReducers({
    reducer: reducerMain
});

export default reducer;